#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path, PurePosixPath
from typing import Iterable

PACKAGE_POLICY_VERSION = "FORGEPY-PACKAGE-POLICY-1.8-F777"
TRANSIENT_TOP_LEVEL = {
    ".git", ".forge", "__pycache__", "logs", "artifacts", "updates",
    "hotfix-backups", "dist", "build", "builds", "target", "bin", "obj",
    "node_modules", ".venv", "venv", ".cache", ".pytest_cache", ".idea", ".vs",
    "installer-staging",
}
# Historical in-repository copy. Root app/ is the only source authority.
LEGACY_MIRROR_TOP_LEVEL = {"forgepy"}
TRANSIENT_EXACT_PATHS = {"native/forge-rs/Cargo.lock"}
# Governed output that is regenerated by the Full Gate and must never be a self-update preimage blocker.
PATCH_REGENERATED_EXACT_PATHS = {"FORGEPY_PACKAGE_MANIFEST.json"}
TRANSIENT_FILE_NAMES = {
    "forgepy.settings.json", "forge.settings.json", "vault.settings.json",
}
TRANSIENT_SUFFIXES = {".pyc", ".pyo", ".dmp", ".mdmp"}
# Build/cache folders that are always transient, including inside the Rust successor lane.
TRANSIENT_ANYWHERE = {"__pycache__", ".pytest_cache", ".cache", "target", "node_modules", ".venv", "venv"}


def normalize_rel(path: str | Path) -> str:
    raw = str(path).replace("\\", "/").strip("/")
    if not raw:
        return ""
    p = PurePosixPath(raw)
    return "/".join(p.parts)


def classification(path: str | Path) -> str:
    rel = normalize_rel(path)
    if not rel:
        return "invalid"
    if rel.casefold() in {x.casefold() for x in TRANSIENT_EXACT_PATHS}:
        return "runtime-transient"
    p = PurePosixPath(rel)
    folded = [part.casefold() for part in p.parts]
    if folded and folded[0] in LEGACY_MIRROR_TOP_LEVEL:
        return "legacy-mirror"
    if folded and folded[0] in {x.casefold() for x in TRANSIENT_TOP_LEVEL}:
        return "runtime-transient"
    if any(part in TRANSIENT_ANYWHERE for part in folded):
        return "runtime-transient"
    if p.name.casefold() in {x.casefold() for x in TRANSIENT_FILE_NAMES}:
        return "machine-local"
    if p.suffix.casefold() in TRANSIENT_SUFFIXES:
        return "runtime-transient"
    return "governed"


def is_governed(path: str | Path) -> bool:
    return classification(path) == "governed"



def patch_regenerated(path: str | Path) -> bool:
    rel = normalize_rel(path)
    return rel.casefold() in {x.casefold() for x in PATCH_REGENERATED_EXACT_PATHS}


def self_update_safe(path: str | Path) -> bool:
    return is_governed(path)


def filter_governed(paths: Iterable[str | Path]) -> list[str]:
    return [normalize_rel(p) for p in paths if is_governed(p)]
